# Generated by Django 3.2 on 2022-07-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_lawyer_exper_lowyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='emnumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
