# Generated by Django 3.2 on 2022-07-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0003_lawyer_emnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='times',
        ),
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
