# Generated by Django 3.2 on 2022-08-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0004_auto_20220729_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
