# Generated by Django 4.1.1 on 2023-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0005_auto_20220813_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
